version: '3.8'

services:
  app:
    build: .
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=production
      - PORT=10000
      - MONGO_URI=${MONGO_URI}
      - UPLOADS_DIR=uploads/
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - ./backend/uploads:/app/backend/uploads
    restart: unless-stopped 